<a href="https://colab.research.google.com/github/basakozgurr/bedlab_project/blob/main/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.6.0+cu124


In [ ]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix=torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim


2

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
tensor=torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
random_tensors=torch.rand(2,3,4)
random_tensors

tensor([[[0.4171, 0.6965, 0.0972, 0.7100],
         [0.6093, 0.3269, 0.3196, 0.8007],
         [0.5820, 0.0977, 0.1955, 0.5121]],

        [[0.6370, 0.0538, 0.0726, 0.7934],
         [0.5189, 0.0899, 0.8559, 0.1469],
         [0.1329, 0.5448, 0.5354, 0.2806]]])

In [ ]:
random_tensors.ndim

3

In [ ]:
random_image_size_tensors=torch.rand(size=(3,224,224))
random_image_size_tensors.shape,random_image_size_tensors.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensors

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones*random_tensors

tensor([[[0.4171, 0.6965, 0.0972, 0.7100],
         [0.6093, 0.3269, 0.3196, 0.8007],
         [0.5820, 0.0977, 0.1955, 0.5121]],

        [[0.6370, 0.0538, 0.0726, 0.7934],
         [0.5189, 0.0899, 0.8559, 0.1469],
         [0.1329, 0.5448, 0.5354, 0.2806]]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
torch.arange(1,11)
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=torch.float16,device=None,requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [ ]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)